site_name: STARTbio
site_url: https://artbio.github.io/startbio/
repo_url: https://github.com/ARTbio/startbio
repo_name: ARTbio/startbio
theme:
  name: 'material'
  logo: assets/startbio_icon.png
  font:
    text: Noto Sans Display  # Confortaa, Open Sans, Shippori Antique,
  palette:
    scheme: default
    primary: black
  icon:
    repo: fontawesome/brands/github
    admonition:
      danger: octicons/alert-fill-12
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
    - navigation.top
    - navigation.prune
    - navigation.footer
#    - toc.integrate
    - content.tabs.link
    - content.code.copy
    - content.action.view
    - content.action.edit

plugins:
  - search  # TRÈS IMPORTANT: pour garder la barre de recherche
  - unused_files:
      # Ne mettez pas 'dir:' pour scanner tout le dossier 'docs/'
      strict: false
      file_types: ["png", "jpg", "jpeg", "gif", "svg"]

nav:
  - Home: index.md

  - Interactive Online Companionship (IOC):

    - IOC on bulk RNAseq analysis:
        - Provisional Program / Schedule: bulk_RNAseq-IOC/00_IOC_RNAseq_program.md
        - Week 0:
            - Introduction - Week-0: bulk_RNAseq-IOC/01_IOC_RNAseq_week_00.md
            - Week 0 exercises: bulk_RNAseq-IOC/02_exercises_week_00.md
        - Week 1:
          - Review on week-0 work: bulk_RNAseq-IOC/02_exercices_week_00_review.md
          - Analysis Overwiew:
            - The Key idea: bulk_RNAseq-IOC/03_readcounts.md
            - RNAseq librairies:
              - cDNA synthesis: bulk_RNAseq-IOC/04_cDNAs.md
              - Inserts and sequencing strategies: bulk_RNAseq-IOC/05_sequencing_strategies.md
            - Sequence Quality and Read Filtering: bulk_RNAseq-IOC/06_sequence_quality_read_filtering.md
            - Transcript Quantification: bulk_RNAseq-IOC/07_transcript_quant.md
            - Statistical Analysis of Differential expression: bulk_RNAseq-IOC/08_RNAseq_DE.md
            - Understanding of all your experimental procedures: bulk_RNAseq-IOC/09_outline_conclusion.md
          - Week 1 exercises:
            - Use case PRJNA630433:
              - Presentation: bulk_RNAseq-IOC/10_PRJNA630433_presentation.md
              - Data upload: bulk_RNAseq-IOC/11_uploads.md
              - Quality Control: bulk_RNAseq-IOC/12_QC.md
        - Week 2:
          - Review on week-1 work: bulk_RNAseq-IOC/13_exercices_week_01_review.md
          - Read Mapping overview:
            - Reference genomes: bulk_RNAseq-IOC/14_reference_genomes.md
            - Aligners: bulk_RNAseq-IOC/14-1_aligners.md
            - Splice-aware alignment: bulk_RNAseq-IOC/15_splice_aware_mapping.md
          - Week 2 exercices:
            - Library strandness: bulk_RNAseq-IOC/16_strandness.md
            - HiSAT2: bulk_RNAseq-IOC/17_hisat2.md
            - STAR: bulk_RNAseq-IOC/18_star.md
            - UCSC visualisation: bulk_RNAseq-IOC/18-1_UCSC_visualisation.md

        - Week 3:
          - Review on week-2 work: bulk_RNAseq-IOC/19_exercices_week_02_review.md
          - Counting reads or fragments: bulk_RNAseq-IOC/20_intro_counting.md
          - Week 3 exercices:
            - FeatureCounts: bulk_RNAseq-IOC/21_FeatureCounts.md
            - HTSeq_counts: bulk_RNAseq-IOC/22_HTSeq_counts.md
            - Count with STAR: bulk_RNAseq-IOC/23_star_counts.md


        - Week 4:
          - Review on week-3 work: bulk_RNAseq-IOC/24_exercices_week_03_review.md
          - Differential Gene Expression Analysis: bulk_RNAseq-IOC/25_DE_intro.md
          - Week 4 exercices:
            - DESeq2: bulk_RNAseq-IOC/26_deseq2.md
            - edgeR: bulk_RNAseq-IOC/27_edgeR.md
            - limma: bulk_RNAseq-IOC/27_1_limma.md
            - DE_manipulations:
              - DESeq2: bulk_RNAseq-IOC/28_manipulation_DEseq2_data.md
              - edgeR: bulk_RNAseq-IOC/28_1_manipulation_edgeR_data.md
              - limma: bulk_RNAseq-IOC/28_2_manipulation_limma_data.md
            - DEseq/edgeR/limma comparison: bulk_RNAseq-IOC/29_0_comparisons.md
            - Volcano plots: bulk_RNAseq-IOC/29_volcano.md

        - Week 5:
          - Review on week-4 work: bulk_RNAseq-IOC/30_exercices_week_04_review.md
          - Gene Ontology Enrichment Analysis: bulk_RNAseq-IOC/31_GO_enrichment_intro.md
          - Week 5 exercices:
            - GOseq: bulk_RNAseq-IOC/32_GOseq.md

        - Week 6:
          - Review on week-5 work: bulk_RNAseq-IOC/33_exercices_week_05_review.md
          - Gene Set Enrichment Analysis (GSEA): bulk_RNAseq-IOC/34_GSEA_intro.md
          - Week 6 exercices:
            - Intro to week 6 exercices: bulk_RNAseq-IOC/35_INTRO_GSEA_exercices.md
            - fGSEA: bulk_RNAseq-IOC/35_GSEA_1.md
            - EGSEA: bulk_RNAseq-IOC/36_GSEA_2.md

        - Week 7:
          - Review on week-6 work: bulk_RNAseq-IOC/40_exercices_week_06_review.md
          - Galaxy Workflows:
            - Introduction: bulk_RNAseq-IOC/41_workflow_intro.md
          - Week 7 exercices:
            - Build your workflow: bulk_RNAseq-IOC/42_workflow_use_1.md

        - Week 8:
          - Review on week-7 work: bulk_RNAseq-IOC/50_exercices_week_07_review.md
          - Recap: bulk_RNAseq-IOC/51_recap.md
          - 20min presentations:
            - Trainee 1: bulk_RNAseq-IOC/52_trainee-1.md
            - Trainee 2: bulk_RNAseq-IOC/53_trainee-2.md
            - Trainne 3: bulk_RNAseq-IOC/54_trainee-3.md

        - External Materials: bulk_RNAseq-IOC/links.md

    - IOC on R:
        - Provisional Program : 
          - Schedule: R-IOC/00_IOC_R_program.md
          - Week 0 - Introduction: R-IOC/01_IOC_R_week_00.md
          - Week 1 - First steps: R-IOC/02_IOC_R_week_01.md
          - Week 2 - Learning vectors and more: R-IOC/03_IOC_R_week_02.md
          - Week 3 - Learning Lists: R-IOC/04_IOC_R_week_03.md
          - Week 4 - Two-dimensional objects: R-IOC/05_IOC_R_week_04.md
          - Week 5 - Level up your code: R-IOC/06_IOC_R_week_05.md
          - Week 6 - Tidyverse: R-IOC/07_IOC_R_week_06.md
          - Week 7 - Data visualisation: R-IOC/08_IOC_R_week_07.md
        - Reference Manual:
          - Variables: R-IOC/r00_variables.md
          - Vectors: R-IOC/r01_vectors.md
          - Operators: R-IOC/r02_operators.md
          - Functions: R-IOC/r03_functions.md
          - Best Practices: R-IOC/r04_bestpractices.md
          - Lists: R-IOC/r05_lists.md
          - Data Frames and Matrices: R-IOC/r06_df_matrices.md
          - Data Import and Export: R-IOC/r07_data_import_export.md
          - Apply & Co: R-IOC/r11_apply.md
          - Conditions: R-IOC/r08_ifelse.md
          - Manipulating data with tidyverse: R-IOC/r10_tidyverse.md
          - Visualization: R-IOC/r09_viz_ggplot2.md
        - Storage room: R-IOC/pick-up.md

    - IOC on Single-cell RNAseq analysis using Seurat in R:
        - Program / Schedule :
          - Schedule : scRNAseq_basics/program_sc.md
          - Week 0 - Introduction, Data Import & Annotation: scRNAseq_basics/00_IOCsc_week0.md
          - Week 1 - Data Processing & High Variable Genes: scRNAseq_basics/01_IOCsc_week1.md
          - Week 2 - Reduction of Dimensionality: scRNAseq_basics/02_IOCsc_week2.md
          - Week 3 - Clustering: scRNAseq_basics/03_IOCsc_week3.md
          - Week 4 - Differential Gene Expression: scRNAseq_basics/04_IOCsc_week4.md
          - Week 5 - Enrichment Analysis (ORA): scRNAseq_basics/05_IOCsc_week5.md
          - Week 6 - Enrichment Analysis (GSEA): scRNAseq_basics/06_IOCsc_week6.md
          - Week 7 - Visualisation: scRNAseq_basics/07_IOCsc_week7.md
        - Reference Manual:
          - Introduction: scRNAseq_basics/introduction.md
          - Prerequisites: scRNAseq_basics/prerequisites.md
          - Initialization of R analysis: scRNAseq_basics/intro_seurat.md
          - Import data: scRNAseq_basics/import.md
          - Preprocessing: scRNAseq_basics/preprocessing.md
          - Reduction of dimensionality: scRNAseq_basics/redim.md
          - Clustering: scRNAseq_basics/clustering.md
          - Cell population identification:
            - Introduction and markers identification:  scRNAseq_basics/intro_markers.md
            - Markers Annotation:
              - Presentation of annotation methods: scRNAseq_basics/marker_annot.md
              - Over-representation analysis: scRNAseq_basics/over.md
              - Gene Set Enrichment Analysis: scRNAseq_basics/gsea.md
            - Cluster annotation: scRNAseq_basics/clusannot.md
          - Comparison between 2 populations: scRNAseq_basics/comp.md
          - Differents visualizations of Seurat: scRNAseq_basics/visualization.md
          - References: scRNAseq_basics/references.md

    -  Introduction to Deep-seq Analysis:
        - INTRODUCTION: deepseq/index.md
        - Illumina sequencing: deepseq/illumina.md
        - Pacific Biosciences SMRT: deepseq/pacbio.md
        - Oxford Nanopore MinION: deepseq/nanopore.md
        - Sequencing facts: deepseq/seq_parameters.md
        - Small RNA library: deepseq/smRNA_lib_prep.md
        - RNA library: deepseq/RNA_lib_prep.md
        - ChIP-seq library: deepseq/chipseq_lib.md
        - Deep Sequencing Applications: deepseq/deepseq_applications.md
        - "Analysis Flowchart:": deepseq/flowchart.md
        - Various aspects of sequence data mining: deepseq/mining.md
        - "Pratical part: Command lines": deepseq/command_lines.md
        - Align reads with bowtie: deepseq/bowtie.md
        - To be continued... with Galaxy: deepseq/galaxy.md
        - BOWTIE ALIGNMENT USING galaxy: deepseq/bowtie_galaxy.md

  - 1Omin2:
    - Grep and Regex (1): ten2/Regex_01.md
    - Python Decorators: ten2/python_decorators.md

  - Galaxy Trainings:

    -  Analyse des Génomes (2025):
        - Analyse des Génomes (2025): AnalyseGenomes_2025/outline.md
        - "Spin off a VM with your Google Cloud Account": AnalyseGenomes_2025/Google_cloud_Account.md
        - START A VIRTUAL MACHINE IN GOOGLE CLOUD ENGINE : AnalyseGenomes_2025/bare-galaxy-google.md
        - DEPLOY A GALAXY SERVER IN THE VM: AnalyseGenomes_2025/deploy-galaxy-server.md
        - MANAGE YOUR GOOGLE VM: AnalyseGenomes_2025/manage_VM.md
        - MANAGE YOUR GALAXY SERVER: AnalyseGenomes_2025/manage_galaxy.md
        - LOAD TRAINING DATA: AnalyseGenomes_2025/Loading_data_in_galaxy.md
        - LAST CHECK BEFORE BUILDING GENOME INDEX: AnalyseGenomes_2025/histories_check.md
        - PREPARE A REFERENCE GENOME: AnalyseGenomes_2025/Preparing_reference.md
        - Format conversion using command lines in your Google VM: AnalyseGenomes_2025/file_parsing_cli.md
        - Format conversion using a galaxy tool: AnalyseGenomes_2025/file_parsing_galaxy.md
        - Running a galaxy workflow: AnalyseGenomes_2025/Run_workflow.md
        - Why administering galaxy ?: AnalyseGenomes_2025/whyadmin.md
        - "EMERGENCY image": AnalyseGenomes_2025/emergency_image.md
        - SUP MATERIAL:
          - BOWTIE ALIGNMENT USING COMMAND LINES: AnalyseGenomes_2025/bowtie_cli.md
          - BOWTIE ALIGNMENT USING GALAXY: AnalyseGenomes_2025/bowtie_galaxy.md
          - SHARE VM IMAGE WITH CLASS STUDENTS: AnalyseGenomes_2025/share_vm_image.md

    -  Run your Galaxy server:
        - INTRODUCTION: Run-Galaxy/index.md
        - STANDALONE GALAXY IN GCP : Run-Galaxy/bare-galaxy-google.md
        - STANDALONE GALAXY IN IFB CLOUD: Run-Galaxy/bare-galaxy-IFB.md
        - AFTER DEPLOYMENT: Run-Galaxy/Run_workflow.md
        - INSTALL GALAXY WITH ANSIBLE: Run-Galaxy/GalaxyKickStart.md
        - LOAD INPUT DATA: Run-Galaxy/Loading_data_in_galaxy.md
        - PREPARE A REFERENCE GENOME: Run-Galaxy/Preparing_reference.md
        - TEST YOUR GALAXY INSTANCE: Run-Galaxy/test_instance.md
        - IN CASE OF EMERGENCY: Run-Galaxy/start_from_image.md
        - ADMIN TOOL KIT: Run-Galaxy/admin_kit.md
        - "Appendix 1: Getting a Google Cloud Engine Account": Run-Galaxy/Google_cloud_Account.md
        - "Appendix 2: Start and stop a Google virtual machine": Run-Galaxy/spin_off_VM.md
        - "Appendix 3: http access to the IFB cloud" : Run-Galaxy/SocksProxy.md
        - "Appendix 4: Galaxy software architecture" : Run-Galaxy/Galaxy_architecture.md
        - "Appendix 5: Install a Galaxy server with Docker": Run-Galaxy/Docker_GalaxyKickStart.md

    - Run a Galaxy workflow for somatic mutation detection in cancers:
        - INTRODUCTION: Run-COH/index.md
    -  Search for chomosome translocations:
        - Introduction: translocations/index.md
        - Sequencing Protocol: translocations/seq.md
        - Lumpy approach: translocations/lumpy_approach.md
        - Trainee connection: translocations/connection.md
        - Prepare the input data history: translocations/import.md
        - Align reads to the human genome: translocations/BWA.md
        - lumpy analysis: translocations/lumpy.md
        - Reformat VCF files for visualization in the UCSC genome browser: translocations/filter_vcf.md
        - Compute the genome read coverage: translocations/coverage.md
        - Data Visualisation in UCSC Genome Browser: translocations/visualisation.md
        - Generate workflow from an history: translocations/workflow.md
        - Run the Lumpy workflow: translocations/run_workflow.md

    -  Reference-based RNAseq analysis:
        - Introduction: reference_based_RNAseq/index.md
        - Pretreatments:
          - Data upload: reference_based_RNAseq/uploads.md
          - Quality control: reference_based_RNAseq/QC.md
        - Outline and general concepts for the RNAseq analysis:
          - RNAseq librairies - cDNA synthesis: reference_based_RNAseq/cDNAs.md
          - RNAseq librairies - Inserts and sequencing strategies: reference_based_RNAseq/sequencing_strategies.md
          - The key idea in Reference-base Expression analysis: reference_based_RNAseq/readcounts.md
          - Reflecting on quality control & “filtering” in RNAseq analysis: reference_based_RNAseq/read_filtering.md
          - Transcript Quantification: reference_based_RNAseq/transcript_quant.md
          - Statistical Analysis of Differential expression: reference_based_RNAseq/RNAseq_DE.md
          - Experimental procedures affect downstream analyses: reference_based_RNAseq/outline_conclusion.md
        - Quality filtering:
          - Optional filtering of reads on sequence quality: reference_based_RNAseq/Cutadapt.md
        - Mapping:
          - Mapping: reference_based_RNAseq/mapping.md
          - RNA STAR: reference_based_RNAseq/star.md
          - HiSAT2: reference_based_RNAseq/hisat2.md
          - BAM inspection: reference_based_RNAseq/bam.md
          - Visualisation of read mapping: reference_based_RNAseq/visu_map.md
        - Analysis of the differential gene expression:
          - Introduction to read counting: reference_based_RNAseq/intro_counting.md
          - Estimation of the strandness: reference_based_RNAseq/strandness.md
          - Count the number of reads per annotated gene: reference_based_RNAseq/count.md
          - Identification of the differentially expressed features - DESeq2: reference_based_RNAseq/DE_intro.md
          - DESeq2 use: reference_based_RNAseq/DEDESeq2.md
          - Volcano Plot: reference_based_RNAseq/volcano.md
          - Visualization of the differentially expressed genes: reference_based_RNAseq/DEseq2visu.md
          - Analysis of functional enrichment among the differentially expressed genes:
            - Introduction: reference_based_RNAseq/GO-intro.md
            - GO: reference_based_RNAseq/GO-tool.md
        - Galaxy Workflows:
          - Introduction: reference_based_RNAseq/workflow_intro.md
          - Example: reference_based_RNAseq/workflow_use.md

    -  Viruses Metagenomics:
        - Metavisitor: metavisitor/index.md
        - Prepare Metavisitor Galaxy instance for analyses: metavisitor/metavisitor_configure_references.md
        - Prepare input data histories: metavisitor/use_cases_input_data.md
        - Use Cases 1-1 to 1-4: metavisitor/use_case_1.md
        - Use Cases 2-1 and 2-2: metavisitor/use_case_2.md
        - Use Case 3-1: metavisitor/use_case_3-1.md
        - Use Case 3-2: metavisitor/use_case_3-2.md
        - Use Case 3-3: metavisitor/use_case_3-3.md
        - Install_Metavisitor:
          - Intro: metavisitor/install_metavisitor.md
          - GalaxyKickStart: metavisitor/metavisitor_ansible.md
          - Docker: metavisitor/metavisitor_docker.md
          - Access and Control Metavisitor Galaxy instance: metavisitor/metavisitor_access_control.md

    -  Download TARGET-AML Data in Galaxy:
        - Introduction: TARGET_download/intro.md
        - Fill your GDC cart: TARGET_download/GDC_cart.md
        - Edit files metadata: TARGET_download/metadata_manipulation.md
        - import files in Galaxy using the edited files metadata: TARGET_download/galaxy_import.md

  - Code Snippets:
    - Terminal Bash: bash_snippets.md
    - Buid your JupyterHub and user kernel: jupyterhub_and_kernels.md
    - The markdown emoji resource: markdown_emoji.md

  - Links: links.md

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - codehilite:
      linenums: true
  - admonition
  - footnotes
  - toc:
      permalink: true
#  - pymdownx.betterem:
#      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      auto_title: false
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
#  - pymdownx.inlinehilite # compete with codehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

      

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - spoiler_files/spoiler.js

extra_css:
  - spoiler_files/spoiler.css